import maelstrom from "../img/maelstrom.jpg";

export default [
    {
        "name": "Maelstrom Elfball",
        "description": "An elfball Commander deck with Maelstrom Wanderer",
        "headboard": {
            "name": "Commander",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        },
        "mainboard": {
            "name": "Mainboard",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        },
        "sideboard": {
            "name": "Extra cards",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        }
    },
    {
        "name": "Seton Druid Storm",
        "description": "Lorem ipsum",
        "headboard": {
            "name": "Commander",
            "cards": [
                { "image": maelstrom }
            ]
        },
        "mainboard": {
            "name": "Mainboard",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        },
        "sideboard": {
            "name": "Extra cards",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        }
    },
    {
        "name": "Kumena Tempo",
        "description": "Lorem ipsum",
        "headboard": {
            "name": "Commander",
            "cards": [
                { "image": maelstrom }
            ]
        },
        "mainboard": {
            "name": "Mainboard",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        },
        "sideboard": {
            "name": "Extra cards",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        }
    },
    {
        "name": "Najeela Tempo",
        "description": "A Competitive Commander deck with Najeela, the Blade-Blossom",
        "headboard": {
            "name": "Commander",
            "cards": [
                { "image": maelstrom }
            ]
        },
        "mainboard": {
            "name": "Mainboard",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        },
        "sideboard": {
            "name": "Extra cards",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        }
    },
    {
        "name": "Temur Canlander",
        "description": "Lorem Ipsum",
        "mainboard": {
            "name": "Mainboard",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        },
        "sideboard": {
            "name": "Extra cards",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        }
    },
    {
        "name": "Pauper Affinity",
        "description": "Lorem Ipsum",
        "mainboard": {
            "name": "Mainboard",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        },
        "sideboard": {
            "name": "Sideboard",
            "cards": [
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom },
                { "image": maelstrom }
            ]
        }
    }
]
